MERGE INTO OUCHNSYS.EAS_TCP_RECRUITBATCH A USING
 (SELECT
  '201809' as BATCHCODE,
  '2018Çï¼¾' as RECRUITBATCHNAME,
  '1' as EDUTYPECODE,
  NULL as STARTTIME,
  NULL as ENDTIME,
  '0' as ISCURRENT,
  TO_DATE('07/13/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS') as CREATETIME
  FROM DUAL) B
ON (A.BATCHCODE = B.BATCHCODE)
WHEN NOT MATCHED THEN 
INSERT (
  BATCHCODE, RECRUITBATCHNAME, EDUTYPECODE, STARTTIME, ENDTIME, 
  ISCURRENT, CREATETIME)
VALUES (
  B.BATCHCODE, B.RECRUITBATCHNAME, B.EDUTYPECODE, B.STARTTIME, B.ENDTIME, 
  B.ISCURRENT, B.CREATETIME)
WHEN MATCHED THEN
UPDATE SET 
  A.RECRUITBATCHNAME = B.RECRUITBATCHNAME,
  A.EDUTYPECODE = B.EDUTYPECODE,
  A.STARTTIME = B.STARTTIME,
  A.ENDTIME = B.ENDTIME,
  A.ISCURRENT = B.ISCURRENT,
  A.CREATETIME = B.CREATETIME;

COMMIT;
