MERGE INTO OUCHNSYS.EAS_SPY_OPENSPYLEARNINGCENTER A USING
eas_spy_openspyleacen_temp B
ON (A.LEARNINGCENTERORGCODE = B.LEARNINGCENTERORGCODE and a.spycode=b.spycode and a.studenttype=b.studenttype and a.professionallevel=b.professionallevel)
WHEN NOT MATCHED THEN 
INSERT (
  SN, SEGMENTORGCODE, LEARNINGCENTERORGCODE, SPYCODE, STUDENTTYPE, 
  PROFESSIONALLEVEL, OPENSTATE, CREATETIME)
VALUES (
  B.SN, B.SEGMENTORGCODE, B.LEARNINGCENTERORGCODE, B.SPYCODE, B.STUDENTTYPE, 
  B.PROFESSIONALLEVEL, B.OPENSTATE, B.CREATETIME)
;
COMMIT;

MERGE INTO OUCHNSYS.EAS_SPY_BASICINFO A USING
EAS_SPY_BASICINFO_temp B
ON (A.spycode = B.spycode)
WHEN NOT MATCHED THEN 
INSERT (
  SN, SPYCODE, SPYDIRECTION, SPYNAME, EDUCATIONCOMMISSIONCODE, 
  CATEGORY, CREATETIME, LEVELCODE, CREATEORG, ISSHARE, 
  SHAREORGCODE, SCOPE, EDUSPYNAME)
VALUES (
  B.SN, B.SPYCODE, B.SPYDIRECTION, B.SPYNAME, B.EDUCATIONCOMMISSIONCODE, 
  B.CATEGORY, B.CREATETIME, B.LEVELCODE, B.CREATEORG, B.ISSHARE, 
  B.SHAREORGCODE, B.SCOPE, B.EDUSPYNAME);
  commit;

  MERGE INTO OUCHNSYS.EAS_SPY_OPENSPYSEGMENT A USING
 EAS_SPY_OPENSPYSEGMENT_temp B
ON (A.SEGMENTCODE = B.SEGMENTCODE and a.SPYCODE=b.SPYCODE and a.STUDENTTYPe=b.STUDENTTYPE and  a.PROFESSIONALLEVEl=b.PROFESSIONALLEVEL)
WHEN NOT MATCHED THEN 
INSERT (
  SN, SEGMENTCODE, SPYCODE, STUDENTTYPE, PROFESSIONALLEVEL, 
  OPENSTATE, CREATETIME)
VALUES (
  B.SN, B.SEGMENTCODE, B.SPYCODE, B.STUDENTTYPE, B.PROFESSIONALLEVEL, 
  B.OPENSTATE, B.CREATETIME);
  commit;

  
  MERGE INTO OUCHNSYS.EAS_SPY_OPENSPYcenter A USING
 EAS_SPY_OPENSPYcenter_temp B
ON (a.SPYCODE=b.SPYCODE and a.STUDENTTYPe=b.STUDENTTYPE and  a.PROFESSIONALLEVEl=b.PROFESSIONALLEVEL)
WHEN NOT MATCHED THEN 
INSERT (
  SN,  SPYCODE, STUDENTTYPE, PROFESSIONALLEVEL, 
  OPENSTATE, CREATETIME)
VALUES (
  B.SN,  B.SPYCODE, B.STUDENTTYPE, B.PROFESSIONALLEVEL, 
  B.OPENSTATE, B.CREATETIME);
  commit;


