SET DEFINE OFF;
MERGE INTO OUCHNSYS.EAS_ORG_BASICINFO A USING
cps_basicinfo b on (A.ORGANIZATIONCODE =b.organizationcode)
WHEN NOT MATCHED THEN 
INSERT (
  ORGANIZATIONID, ORGANIZATIONCODE, ORGANIZATIONNAME, PARENTCODE, ORGANIZATIONTYPE, 
  STATE, CREATETIME, ISINDUSTRY, TEACHSITENO)
VALUES (
  b.ORGANIZATIONID, B.ORGANIZATIONCODE, B.ORGANIZATIONNAME, B.PARENTCODE, B.ORGANIZATIONTYPE, 
  B.STATE, B.CREATETIME, B.ISINDUSTRY, B.TEACHSITENO)
  where B.ORGANIZATIONCODE is not null and B.ORGANIZATIONTYPE is not null
--WHEN MATCHED THEN
--UPDATE SET 
--  A.ORGANIZATIONCODE = B.ORGANIZATIONCODE,
--  A.ORGANIZATIONNAME = B.ORGANIZATIONNAME,
--  A.PARENTCODE = B.PARENTCODE,
--  A.ORGANIZATIONTYPE = B.ORGANIZATIONTYPE,
--  A.STATE = B.STATE,
--  A.CREATETIME = B.CREATETIME,
--  A.ISINDUSTRY = B.ISINDUSTRY,
--  A.TEACHSITENO = B.TEACHSITENO;

COMMIT;
